[build-system]
requires = ["maturin>=1.9,<2.0"]
build-backend = "maturin"

[project]
name = "pyrstest"
requires-python = ">=3.8"
dynamic = ["version"]
dependencies = [
    "trio>=0.27.0",
]

[tool.maturin]
features = ["pyo3/extension-module"]

[dependency-groups]
dev = [
    "maturin>=1.9.6",
]
